/**
 * Expo config plugin — debug-only Android network security config for local DDEV HTTPS (E2E).
 *
 * Why this exists: the app talks to the DDEV test site over HTTPS with a **mkcert** certificate.
 * Android (API 24+) does NOT trust user-added or custom CAs by default, so a debug build can't
 * complete the TLS handshake to `https://*.ddev.site`. This plugin injects a
 * `network_security_config.xml` that, **only in debuggable builds** (`<debug-overrides>`), trusts:
 *   - the system CAs (normal),
 *   - user-installed CAs (so installing the mkcert CA on the emulator just works), and
 *   - a bundled CA at `certs/ddev-rootCA.pem` IF present (deterministic for CI/Maestro).
 *
 * `<debug-overrides>` is ignored in release builds, so this is safe to ship — release TLS is
 * unchanged. `android/` is gitignored + regenerated, so this MUST be a plugin (not a hand edit):
 * it re-applies on every `expo prebuild`.
 *
 * See docs/SMOKE_TESTING.md ("HTTPS to DDEV"). The bundled CA is optional — without it, install
 * the mkcert root CA on the emulator and the `user` trust anchor covers it.
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const BUNDLED_CA_SOURCE = 'certs/ddev-rootCA.pem'; // gitignored (*.pem); supply locally if wanted
const RAW_CA_NAME = 'ddev_rootca.pem'; // → referenced as @raw/ddev_rootca

function buildConfigXml(includeBundledCa) {
  const bundled = includeBundledCa ? '\n        <certificates src="@raw/ddev_rootca" />' : '';
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withDevNetworkSecurity.js — do not edit by hand. -->
<network-security-config>
  <debug-overrides>
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />${bundled}
    </trust-anchors>
  </debug-overrides>
</network-security-config>
`;
}

/** Point <application> at the generated config. */
function withManifestRef(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (application) {
      application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return cfg;
  });
}

/** Write res/xml/network_security_config.xml and copy the bundled CA into res/raw if present. */
function withGeneratedFiles(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const resDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');

      const caSource = path.join(projectRoot, BUNDLED_CA_SOURCE);
      const hasBundledCa = fs.existsSync(caSource);

      if (hasBundledCa) {
        const rawDir = path.join(resDir, 'raw');
        fs.mkdirSync(rawDir, { recursive: true });
        fs.copyFileSync(caSource, path.join(rawDir, RAW_CA_NAME));
      } else {
        console.warn(
          `[withDevNetworkSecurity] ${BUNDLED_CA_SOURCE} not found — trusting user-installed CAs only. ` +
            `Install the mkcert root CA on the emulator, or drop the CA at ${BUNDLED_CA_SOURCE} and re-prebuild.`,
        );
      }

      const xmlDir = path.join(resDir, 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'network_security_config.xml'), buildConfigXml(hasBundledCa));

      return cfg;
    },
  ]);
}

module.exports = function withDevNetworkSecurity(config) {
  return withGeneratedFiles(withManifestRef(config));
};
