/**
 * expo-sqlite connection + Drizzle instance + migration runner.
 *
 * The whole app reads/writes through `db` (offline-first — CLAUDE.md). `enableChangeListener`
 * is required for Drizzle's `useLiveQuery` to react to writes. Migrations (generated by
 * drizzle-kit into database/migrations/) are applied on boot via the `useMigrations` hook,
 * wired in app/_layout.tsx so the UI can show a loading/error state while they run.
 */
import { drizzle } from 'drizzle-orm/expo-sqlite';
import { openDatabaseSync } from 'expo-sqlite';
import * as schema from './schema';

export const DATABASE_NAME = 'tqapp.db';

const sqlite = openDatabaseSync(DATABASE_NAME, { enableChangeListener: true });

export const db = drizzle(sqlite, { schema });

export type DB = typeof db;
